### PR TITLE
Remove lint from test workflows for web and server

### PR DESCRIPTION
**Pull request by alexdanilowicz**
See https://github.com/Left-on-Read/leftonread/commit/67472ca7a60dfab80ea121d117cdde9e380fb661#r47649508

### CODE REVIEW

**Review by Teddarific — CHANGES_REQUESTED** [review]
Wait this is important to have - not everything is auto-fixable e.g. unused variable that this caught earlier. But is what you're getting at there's a conflict between the formatter and the test one? That's a good point that I didn't think of, because I guess the formatter has to run before the test, which I think is the right way to approach this. For full transparency on my logic here, I think we should have a `yarn lint` without the `--fix` blocking merge, since that 100% guarantees the change set is good

**Comment by Teddarific** [comment]
We can maybe do something like:

On PR -> Run Formatter -> When Formatter finishes, run Test. 

I think we can probably add a https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run trigger to the `web-test.yml`. Thoughts? No idea what normal github action structure looks like. Pretty interesting problem

**Comment by Teddarific** [comment]
Also alternative could be creating a `web-pr` workflow to be run on a PR and a `web-main` workflow to be run when commit lands. Less modular, but could be more clear and easier to work with.

**Comment by Teddarific** [comment]
Ugh nvm, you need to do some weird workarounds to get the context right with the `workflow_run` https://stackoverflow.com/questions/63343937/how-to-use-the-github-actions-workflow-run-event.

I'll sleep on this, but I think I'd stand by the fact that we want to run tests probably after the formatter the more I think about it. Formatting can sometimes do unexpected things, and it seems like it'd be best to make sure we're running the test job against EXACTLY what will be committed. Do the workflows run again when the formatter commits to the PR?

**Comment by alexdanilowicz** [comment]
Closing this. We ultimately removed the web and server auto-formatting... but we still have the app/ one set up... https://github.com/Left-on-Read/leftonread/pull/87

We should probably add husky and lint-staged. 
https://github.com/sudo-suhas/lint-staged-multi-pkg

**Pull request closed without merging**
