### PR TITLE
Adding server test workflow

### PR DESCRIPTION
**Pull request by Teddarific**
#61

### CODE REVIEW

**Comment by alexdanilowicz** [comment]
lol at the linter errors

**Comment by alexdanilowicz** [comment]
Is it trying to lint the cached stuff?

**Comment by Teddarific** [comment]
wtf is this lol

**Comment by Teddarific** [comment]
Where the heck is it getting the compiled code, there isn't even a command to compile this build lol

**Comment by Teddarific** [comment]
Ah. `yarn tsc` compiles the code lol

**Pull request merged**
